NumPy: Array Object Exercises, Practice, Solution

link https://www.w3resource.com/python-exercises/numpy/index.php

1. Write a NumPy program to print the NumPy version on your system.

In [3]:
import numpy as np

# Print NumPy version
print("NumPy version:", np.__version__)

NumPy version: 1.26.4


2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32]

One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [9]:
List = [12.23, 13.32, 100, 36.32]

Np_array = np.array(List)

# Print the numpy array
print(Np_array)
# Print the numpy array type
print(type(Np_array))

[ 12.23  13.32 100.    36.32]
<class 'numpy.ndarray'>


3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:

[[ 2 3 4]

[ 5 6 7]

[ 8 9 10]]

In [10]:
# Create a 3x3 matrix with values ranging from 2 to 10
Np_matrix = np.arange(2, 11).reshape(3, 3)

# Print the matrix
print(Np_matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11

[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [14]:
# Create a null vector of size 10
Np_array = np.zeros(10)

# Update the sixth value to 11
Np_array[6] = 11

# Print the array
print(Np_array)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


5. Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [15]:
# Create a vector with values ranging from 12 to 38
Np_array = np.arange(12, 38)

# Print the array
print(Np_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


6. Write a NumPy program to reverse an array (the first element becomes the last).

Original array:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Reverse array:

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [17]:
# Create a vector with values ranging from 12 to 38
Np_array = np.arange(12, 38)

# Reverse the array
Reversed_array = np.flip(Np_array)

# Print the reversed array
print(Reversed_array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


7. Write a NumPy program to convert an array to a floating type.

Sample output:

Original array

[1, 2, 3, 4]

Array converted to a float type:

[ 1. 2. 3. 4.]

In [18]:
# Create a vector with values ranging from 1 to 5
Np_array = np.arange(1, 5)

# Convert the array to float type
Np_float_array = Np_array.astype(float)

# Print the float array
print(Np_float_array)

[1. 2. 3. 4.]


8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

Expected Output:

Original array:

[[ 1. 1. 1. 1. 1.]

...................

[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array

[[ 1. 1. 1. 1. 1.]

...................

[ 1. 1. 1. 1. 1.]]

In [24]:
# Specify the dimensions of the 2D array
rows, cols = 5, 5

# Create the original array with 1 on the border and 0 inside
Np_array = np.ones((rows, cols))

# Print original array
print(Np_array)
print()

# Set the inner values to 0
Np_array[1:-1, 1:-1] = 0

# Print converted array
print(Np_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Write a NumPy program to add a border (filled with 0's) around an existing array.
Expected Output:

Original array:

[[ 1. 1. 1.]

[ 1. 1. 1.]

[ 1. 1. 1.]]

1 on the border and 0 inside in the array

[[ 0. 0. 0. 0. 0.]

...........

[ 0. 0. 0. 0. 0.]]

In [30]:
# Specify the dimensions of the 2D array
rows, cols = 5, 5

# Create the original array with 1 on the border and 0 inside
Np_array = np.ones((rows, cols))

# Print original array
print("Original array:")
print(Np_array)

# Add a border of 0's around the original array
Np_border_array = np.pad(Np_array, pad_width=1, mode='constant', constant_values=0)

# Print array with the added border
print("\nArray with the added border:")
print(Np_border_array)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Array with the added border:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


10. Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

Checkerboard pattern:

[[0 1 0 1 0 1 0 1]

..........

[0 1 0 1 0 1 0 1]

[1 0 1 0 1 0 1 0]]

In [41]:
# Specify the dimensions of the 2D array
rows, cols = 5, 5

# Create the original array with 1 on the border and 0 inside
Np_array = np.ones((rows, cols))

# Print original array
print("Original array:")
print(Np_array)

# Fill the even rows and columns with 1
Np_array[::2, ::2] = 0
Np_array[1::2, 1::2] = 0

# Print array with the new pattern
print("\nArray with the new pattern:")
print(Np_array)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Array with the new pattern:
[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


11. Write a NumPy program to convert a list and tuple into arrays.

List to array:

[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
[1 2 3]]

In [48]:
import numpy as np

# Convert a list to an array
List_data = [1, 2, 3, 4, 5, 6, 7, 8]
Array_from_list = np.array(List_data)

# Convert a tuple to a 2D array
Tuple_data = ((8, 4, 6), (1, 2, 3))
Array_from_tuple = np.array(Tuple_data)

# Print the results
print("List to array:")
print(Array_from_list)

print("\nTuple to array:")
print(Array_from_tuple)


List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
 [1 2 3]]


12. Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:

[10, 20, 30]

After append values to the end of the array:

[10 20 30 40 50 60 70 80 90]

In [49]:
import numpy as np

# Create the original array
original_array = np.array([10, 20, 30])

# Print the original array
print("Original array:")
print(original_array)

# Values to append
values_to_append = np.array([40, 50, 60, 70, 80, 90])

# Append values to the end of the array
result_array = np.append(original_array, values_to_append)

# Print the array after appending values
print("\nAfter append values to the end of the array:")
print(result_array)


Original array:
[10 20 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


13. Write a NumPy program to create an empty and full array.

Expected Output:

[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]

[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]

[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]


[[6 6 6]

[6 6 6]

[6 6 6]]

In [56]:
# Create an empty array
empty_array = np.empty((3, 4))

# Create a full array with a specified value (6 in this case)
full_array = np.full((3, 3), 6)

# Print the empty and full arrays
print("Empty array:")
print(empty_array)

print("\nFull array:")
print(full_array)


Empty array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Full array:
[[6 6 6]
 [6 6 6]
 [6 6 6]]


14. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

Sample Array [0, 12, 45.21, 34, 99.91]

[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

Expected Output:

Values in Fahrenheit degrees:

[ 0. 12. 45.21 34. 99.91 32. ]

Values in Centigrade degrees:

[-17.78 -11.11 7.34 1.11 37.73 0. ]

In [62]:
# Sample array in Centigrade
centigrade_array = np.array([-17.78, -11.11, 7.34,1.11, 37.73, 0.])

# Convert Centigrade to Fahrenheit
fahrenheit_array = (centigrade_array * 9/5) + 32

# Print the values in Fahrenheit and Centigrade
print("Values in Fahrenheit degrees:")
print(fahrenheit_array.round(2))

print("\nValues in Centigrade degrees:")
print(centigrade_array)


Values in Fahrenheit degrees:
[-0.   12.   45.21 34.   99.91 32.  ]

Values in Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

Expected Output:

Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

Real part of the array:

[ 1. 0.70710678]

Imaginary part of the array:

[ 0. 0.70710678]

In [63]:
# Original array of complex numbers
complex_array = np.array([1.0 + 0.0j, 0.70710678 + 0.70710678j])

# Print the original array
print("Original array", complex_array)

# Find the real and imaginary parts
real_part = np.real(complex_array)
imaginary_part = np.imag(complex_array)

# Print the real and imaginary part
print("Real part of the array:")
print(real_part)

print("\nImaginary part of the array:")
print(imaginary_part)

Original array [1.        +0.j         0.70710678+0.70710678j]
Real part of the array:
[1.         0.70710678]

Imaginary part of the array:
[0.         0.70710678]


16. Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.

Expected Output:

Size of the array: 3

Length of one array element in bytes: 8

Total bytes consumed by the elements of the array: 24

In [64]:
import numpy as np

# Create an array
my_array = np.array([1, 2, 3])

# Find the number of elements in the array
array_size = my_array.size

# Find the length of one array element in bytes
element_size = my_array.itemsize

# Find the total bytes consumed by the elements of the array
total_bytes = my_array.nbytes

# Print the results
print("Size of the array:", array_size)
print("Length of one array element in bytes:", element_size)
print("Total bytes consumed by the elements of the array:", total_bytes)

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

Expected Output:

Array1: [ 0 10 20 40 60]

Array2: [0, 40]

Compare each element of array1 and array2

[ True False False True False]

In [65]:
import numpy as np

# Define the arrays
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])

# Use the np.isin() function to compare each element of array1 and array2
result = np.isin(array1, array2)

# Print the results
print("Array1:", array1)
print("Array2:", array2)
print("Compare each element of array1 and array2:")
print(result)


Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
Compare each element of array1 and array2:
[ True False False  True False]


18. Write a NumPy program to find common values between two arrays.

Expected Output:

Array1: [ 0 10 20 40 60]

Array2: [10, 30, 40]

Common values between two arrays:

[10 40]

In [66]:
# Define the arrays
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

# Find common values using np.intersect1d()
common_values = np.intersect1d(array1, array2)

# Print the results
print("Array1:", array1)
print("Array2:", array2)
print("Common values between two arrays:")
print(common_values)

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


19. Write a NumPy program to get the unique elements of an array.
Expected Output:

Original array:

[10 10 20 20 30 30]

Unique elements of the above array:

[10 20 30]

Original array:

[[1 1]

[2 3]]

Unique elements of the above array:

[1 2 3]

In [67]:
# Original array 1
array1 = np.array([10, 10, 20, 20, 30, 30])

# Print the original array
print("Original array:")
print(array1)

# Get unique elements of array1
unique_elements1 = np.unique(array1)

# Print unique elements of array1
print("Unique elements of the above array:")
print(unique_elements1)

# Original array 2
array2 = np.array([[1, 1], [2, 3]])

# Print the original array
print("\nOriginal array:")
print(array2)

# Get unique elements of array2
unique_elements2 = np.unique(array2)

# Print unique elements of array2
print("Unique elements of the above array:")
print(unique_elements2)


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]

Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


20. Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in array2.
Expected Output:


Array1: [ 0 10 20 40 60 80]

Array2: [10, 30, 40, 50, 70, 90]

Set difference between two arrays:

[ 0 20 60 80]

In [70]:
import numpy as np

# Define the arrays
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

# Find the set difference using np.setdiff1d()
set_difference = np.setdiff1d(array1, array2)

# Print the results
print("Array1:", array1)
print("Array2:", array2)
print("Set difference between two arrays:")
print(set_difference)


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays:
[ 0 20 60 80]
